# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

irt_like <- function(X, mX, pr, wts) {
    .Call(`_PACERcpp_irt_like`, X, mX, pr, wts)
}

rcpparma_hello_world <- function() {
    .Call(`_PACERcpp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_PACERcpp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_PACERcpp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_PACERcpp_rcpparma_bothproducts`, x)
}

